# Analisis Financiero:
- Clasificación de categorias
- Clasificación de perfil financiero
- Recomendaciones Automaticas

In [1]:
!pip install -q scikit-learn==1.9.0 joblib==1.5.3
#Python 3.12.2

[notice] A new release of pip is available: 24.0 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# Librerias
import pandas as pd
import numpy as np
import os
import joblib

## Importar y conocer la base de datos

In [3]:
# LLamando dataset
df1 = pd.read_csv("datasets/personal_finance_1.csv")
df1.head(10)

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense
5,2020-01-14,Benefit suggest page southern.,Shopping,448.68,Expense
6,2020-01-18,By two bad fall pick.,Food & Drink,1520.03,Expense
7,2020-01-19,Court attorney product significant world.,Other,3287.00,Income
8,2020-01-21,Herself law.,Entertainment,1914.85,Expense
9,2020-01-25,Have decide environment.,Rent,766.06,Expense

In [4]:
df2 = pd.read_csv("datasets/personal_finance_2.csv")
df2.head(10)

,date,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,financial_scenario,credit_score,debt_to_income_ratio,loan_payment,...,discretionary_spending,essential_spending,income_type,rent_or_mortgage,category,cash_flow_status,financial_advice_score,financial_stress_level,actual_savings,savings_goal_met
0,2019-01-01,1584,3119.58,3212.07,0.38,3676.11,inflation,721.0,0.56,125.77,...,857.55,1910.85,Freelance,1501.65,Investments,Positive,8.3,Low,0.00,0
1,2019-01-31,1045,3262.44,3732.81,0.10,2607.17,inflation,670.0,0.42,454.19,...,534.51,3165.20,Salary,1603.17,Investments,Positive,22.6,Low,0.00,0
2,2019-03-02,1756,2931.20,3335.58,0.15,3004.14,inflation,691.0,0.24,971.82,...,353.67,1504.56,Freelance,1097.82,Healthcare,Positive,58.8,Low,0.00,0
3,2019-04-01,1724,3506.79,2327.59,0.17,3346.97,normal,717.0,0.16,482.76,...,594.08,1450.72,Freelance,1155.64,Groceries,Positive,74.5,Low,1179.20,0
4,2019-05-01,1600,4606.87,2182.58,0.34,2670.09,inflation,795.0,0.25,263.74,...,556.86,1000.00,Salary,1170.86,Utilities,Negative,38.7,High,2424.29,0
5,2019-05-31,1985,4028.39,3876.57,0.26,2079.72,recession,643.0,0.43,323.20,...,431.04,2330.01,Salary,548.67,Healthcare,Positive,53.7,Medium,151.82,0
6,2019-06-30,1194,4145.45,3035.61,0.15,2215.80,normal,683.0,0.30,609.88,...,443.50,2860.30,Freelance,637.04,Transportation,Positive,74.7,High,1109.84,0
7,2019-07-30,1600,3202.37,2689.51,0.25,3650.48,normal,655.0,0.24,524.64,...,602.88,3526.55,Salary,1453.18,Entertainment,Neutral,83.1,Medium,512.86,0
8,2019-08-29,1835,4765.11,2628.56,0.06,2813.81,normal,715.0,0.52,103.30,...,733.67,2503.65,Salary,1675.75,Education,Negative,71.6,Low,2136.55,0
9,2019-09-28,1454,3581.79,3370.80,0.13,2195.92,normal,749.0,0.52,643.48,...,464.34,1691.26,Salary,682.16,Entertainment,Positive,77.9,High,210.99,0

In [5]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    3000 non-null   str
 1   user_id                 3000 non-null   int64
 2   monthly_income          3000 non-null   float64
 3   monthly_expense_total   3000 non-null   float64
 4   savings_rate            3000 non-null   float64
 5   budget_goal             3000 non-null   float64
 6   financial_scenario      3000 non-null   str
 7   credit_score            3000 non-null   float64
 8   debt_to_income_ratio    3000 non-null   float64
 9   loan_payment            3000 non-null   float64
 10  investment_amount       3000 non-null   float64
 11  subscription_services   3000 non-null   int64
 12  emergency_fund          3000 non-null   float64
 13  transaction_count       3000 non-null   int64
 14  fraud_flag              3000 non-null   int64
 15  discretionary_spending  3000 non-null   float64
 16  essential_spending      3000 non-null   float64
 17  income_type             3000 non-null   str
 18  rent_or_mortgage        3000 non-null   float64
 19  category                3000 non-null   str
 20  cash_flow_status        3000 non-null   str
 21  financial_advice_score  3000 non-null   float64
 22  financial_stress_level  3000 non-null   str
 23  actual_savings          3000 non-null   float64
 24  savings_goal_met        3000 non-null   int64
dtypes: float64(14), int64(5), str(6)
memory usage: 719.1 KB

In [6]:
#Renombrar Columnas
traduccion = {
    'date': 'fecha',
    'user_id': 'id_usuario',
    'monthly_income': 'ingreso_mensual',
    'monthly_expense_total': 'gasto_mensual_total',
    'savings_rate': 'tasa_ahorro',
    'budget_goal': 'objetivo_presupuesto',
    'financial_scenario': 'escenario_financiero',
    'credit_score': 'puntaje_crediticio',
    'debt_to_income_ratio': 'relacion_deuda_ingreso',
    'loan_payment': 'pago_prestamo',
    'investment_amount': 'monto_inversion',
    'subscription_services': 'servicios_suscripcion',
    'emergency_fund': 'fondo_emergencia',
    'transaction_count': 'cantidad_transacciones',
    'fraud_flag': 'indicador_fraude',
    'discretionary_spending': 'gastos_discrecionales',
    'essential_spending': 'gastos_esenciales',
    'income_type': 'tipo_ingreso',
    'rent_or_mortgage': 'alquiler_o_hipoteca',
    'category': 'categoria',
    'cash_flow_status': 'estado_flujo_caja',
    'financial_advice_score': 'puntaje_recomendacion_financiera',
    'financial_stress_level': 'nivel_estres_financiero',
    'actual_savings': 'ahorro_real',
    'savings_goal_met': 'meta_ahorro_cumplida'
}

df2.rename(columns=traduccion, inplace=True)
print(df2.columns.tolist())

['fecha', 'id_usuario', 'ingreso_mensual', 'gasto_mensual_total', 'tasa_ahorro', 'objetivo_presupuesto', 'escenario_financiero', 'puntaje_crediticio', 'relacion_deuda_ingreso', 'pago_prestamo', 'monto_inversion', 'servicios_suscripcion', 'fondo_emergencia', 'cantidad_transacciones', 'indicador_fraude', 'gastos_discrecionales', 'gastos_esenciales', 'tipo_ingreso', 'alquiler_o_hipoteca', 'categoria', 'estado_flujo_caja', 'puntaje_recomendacion_financiera', 'nivel_estres_financiero', 'ahorro_real', 'meta_ahorro_cumplida']

In [7]:
for columna in df2.columns:
    print(f"\n=== {columna} ===")
    print(df2[columna].unique())

=== fecha ===
<ArrowStringArray>
['2019-01-01', '2019-01-31', '2019-03-02', '2019-04-01', '2019-05-01',
 '2019-05-31', '2019-06-30', '2019-07-30', '2019-08-29', '2019-09-28',
 '2019-10-28', '2019-11-27', '2019-12-27', '2020-01-26', '2020-02-25',
 '2020-03-26', '2020-04-25', '2020-05-25', '2020-06-24', '2020-07-24',
 '2020-08-23', '2020-09-22', '2020-10-22', '2020-11-21', '2020-12-21',
 '2021-01-20', '2021-02-19', '2021-03-21', '2021-04-20', '2021-05-20',
 '2021-06-19', '2021-07-19', '2021-08-18', '2021-09-17', '2021-10-17',
 '2021-11-16', '2021-12-16', '2022-01-15', '2022-02-14', '2022-03-16',
 '2022-04-15', '2022-05-15', '2022-06-14', '2022-07-14', '2022-08-13',
 '2022-09-12', '2022-10-12', '2022-11-11', '2022-12-11', '2023-01-10',
 '2023-02-09', '2023-03-11', '2023-04-10', '2023-05-10', '2023-06-09',
 '2023-07-09', '2023-08-08', '2023-09-07', '2023-10-07', '2023-11-06']
Length: 60, dtype: str

=== id_usuario ===
[1584 1045 1756 1724 1600 1985 1194 1835 1454 1357 1403 1884 1675 1750
 1222 1050 1234 1447 1347 1918 1879 1057 1129 1680 1621 1998 1058 1334
 1256 1421 1456 1974 1730 1340 1794 1776 1173 1482 1913 1529 1737 1205
 1957 1983 1206 1984 1368 1443 1506 1942 1353 1477 1657 1275 1908 1585
 1177 1900 1213 1855 1094 1483 1512 1458 1038 1595 1511 1084 1799 1866
 1949 1355 1166 1694 1230 1306 1856 1310 1332 1071 1371 1938 1260 1277
 1446 1917 1209 1896 1335 1604 1895 1662 1461 1243 1894 1827 1063 1579
 1370 1807 1214 1128 1048 1453 1386 1962 1701 1978 1410 1389 1997 1577
 1965 1333 1608 1527 1905 1925 1120 1061 1857 1178 1563 1788 1759 1718
 1250 1671 1224 1947 1538 1070 1568 1561 1726 1109 1532 1433 1469 1191
 1975 1611 1869 1247 1117 1401 1805 1808 1733 1317 1491 1643 1865 1889
 1760 1845 1300 1639 1722 1351 1432 1077 1848 1254 1810 1928 1229 1320
 1295 1784 1283 1567 1634 1800 1108 1521 1749 1244 1852 1849 1770 1971
 1439 1196 1239 1183 1542 1018 1715 1419 1287 1528 1271 1119 1322 1863
 1510 1199 1005 1145 1391 1829 1578 1026 1329 1961 1798 1822 1623 1615
 1161 1358 1676 1180 1384 1637 1844 1236 1398 1652 1834 1994 1314 1950
 1982 1891 1484 1415 1580 1392 1031 1219 1778 1697 1207 1624 1543 1158
 1032 1124 1487 1378 1804 1122 1223 1683 1875 1867 1932 1192 1259 1777
 1390 1502 1036 1743 1037 1165 1113 1953 1311 1702 1132 1536 1656 1587
 1029 1924 1066 1605 1252 1251 1945 1278 1874 1115 1713 1540 1382 1586
 1719 1588 1279 1424 1853 1959 1168 1176 1171 1714 1654 1082 1169 1399
 1134 1121 1020 1264 1341 1442 1819 1478 1837 1762 1682 1397 1873 1345
 1030 1661 1562 1618 1325 1023 1286 1080 1545 1211 1056 1060 1941 1375
 1899 1242 1632 1920 1073 1796 1479 1553 1816 1494 1980 1812 1626 1426
 1526 1407 1783 1116 1309 1921 1103 1890 1348 1034 1655 1573 1847 1589
 1274 1922 1598 1468 1495 1083 1903 1040 1248 1897 1059 1646 1650 1075
 1572 1659 1136 1289 1631 1293 1175 1520 1373 1493 1138 1416 1331 1055
 1868 1434 1201 1698 1253 1352 1431 1282 1181 1504 1305 1114 1438 1633
 1498 1739 1716 1692 1195 1152 1097 1744 1385 1255 1133 1539 1046 1099
 1428 1157 1065 1533 1649 1846 1374 1910 1833 1464 1388 1336 1003 1666
 1574 1992 1771 1141 1267 1599 1673 1806 1705 1764 1068 1221 1977 1926
 1616 1989 1127 1647 1338 1042 1216 1172 1163 1463 1522 1968 1888 1767
 1603 1220 1369 1911 1423 1123 1112 1885 1828 1906 1754 1448 1160 1734
 1203 1670 1933 1789 1592 1408 1785 1485 1285 1051 1372 1672 1280 1524
 1831 1383 1323 1741 1021 1582 1395 1732 1787 1803 1751 1014 1167 1164
 1472 1156 1958 1870 1979 1752 1930 1154 1963 1674 1218 1081 1288 1919
 1147 1955 1597 1473 1570 1826 1027 1864 1583 1039 1782 1262 1516 1232
 1197 1422 1552 1047 1394 1406 1404 1886 1466 1318 1818 1459 1449 1581
 1544 1727 1312 1452 1736 1245 1840 1272 1024 1043 1076 1802 1594 1258
 1425 1153 1668 1665 1601 1226 1294 1892 1350 1327 1215 1677 1111 1842
 1324 1189 1427 1912 1854 1198 1339 1411 1851 1074 1893 1641 1091 1107
 1217 1517 1882 1560 1100 1772 1337 1753 1530 1326 1790 1379 1142 1746
 1880 1944 1909 1200 1687 1613 1131 1814 1186 1658 1204 1067 1531 1500
 1707 1617 1396 1418 1470 1612 1839 1349 1304 1934 1096 1860 1444 1575
 1193 1774 1791 1937 1555 1002 1298 1946 1914 1041 1966 1270 1717 1190
 1622 1017 1550 1534 1238 1781 1809 1346 1606 1773 1387 1614 1566 1763
 1690 1663 1939 1033 1010 1296 1723 1012 1044 1490 1898 1607 1118 1001
 1973 1703 1775 1667 1140 1079 1035 1729 1009 1999 1755 1354 1095 1660
 1571 1779 1518 1901 1664 1987 1877 1841 1445 1720 1878 1344 1970 1105
 1551 1268 1313 1052 1006 1801 1321 1475 1092 1993 1308 1155 1465 1476
 1125 1467 1328 1681 1028 1455 1513 1951 1915 1684 1515 1101 1000 1711
 1929 1104 1731 1990 1481 1126 1137 1297 1019 1821 1923 1016 1149 1549
 1981 1170 1725 1679 1462 1202 1457 1859 1497 1823 1862 1836 1645 1380
 1593 1266 1501 1053 1499 1210 1728 1704 1904 1986 1187 1087 1817 1738
 1228 1235 1402 1936 1276 1261 1907 1969 1013 1069 1768 1956 1976 1735
 1557 1629 1876 1861 1179 1602 1960 1249 1362 1554 1284 1678 1098 1015
 1412 1246 1793 1078 1525 1653 1685 1231 1619 1086 1182 1541 1710 1227
 1025 1830 1299 1400 1548 1450 1883 1377 1290 1535 1596 1359 1591 1669
 1471 1150 1642 1625 1927 1492 1547 1565 1240 1420 1638 1435 1151 1745
 1721 1609 1858 1144 1330 1556 1811 1146 1748 1519 1085 1486 1514 1273
 1072 1393 1316 1758 1212 1627 1148 1916 1832 1795 1740 1995 1488 1451
 1343 1628 1007 1413 1474 1843 1696 1011 1651 1635 1102 1700 1695 1319
 1636 1503 1902 1302 1361 1699 1263 1237 1546 1159 1440 1706 1871 1480
 1940 1507 1693 1414 1004 1376 1964 1090 1064 1184 1825 1436 1780 1269
 1640 1689 1742 1709 1496 1991 1505 1417 1106 1089 1437 1948 1620 1838
 1088 1460 1747 1881 1509 1797 1769 1931 1303 1208 1954 1610 1943 1988
 1824 1708 1054 1688 1523 1489 1367 1315 1757 1813 1537 1241 1291 1363
 1872 1409 1972 1265 1292 1967]

=== ingreso_mensual ===
[3119.58 3262.44 2931.2  ... 3691.1  3133.24 4090.06]

=== gasto_mensual_total ===
[3212.07 3732.81 3335.58 ... 3228.05 4335.72 3546.83]

=== tasa_ahorro ===
[0.38 0.1  0.15 0.17 0.34 0.26 0.25 0.06 0.13 0.23 0.29 0.24 0.16 0.3
 0.14 0.22 0.28 0.18 0.4  0.05 0.32 0.08 0.39 0.31 0.37 0.07 0.09 0.36
 0.27 0.33 0.11 0.21 0.2  0.19 0.12 0.35]

=== objetivo_presupuesto ===
[3676.11 2607.17 3004.14 ... 3893.53 2854.72 2365.61]

=== escenario_financiero ===
<ArrowStringArray>
['inflation', 'normal', 'recession']
Length: 3, dtype: str

=== puntaje_crediticio ===
[721. 670. 691. 717. 795. 643. 683. 655. 715. 749. 611. 669. 647. 739.
 620. 631. 676. 743. 759. 694. 706. 661. 609. 665. 662. 617. 619. 690.
 633. 736. 771. 718. 602. 731. 632. 689. 635. 599. 728. 720. 744. 705.
 614. 561. 657. 700. 630. 688. 750. 675. 695. 645. 649. 764. 658. 726.
 692. 727. 613. 753. 714. 612. 628. 682. 668. 681. 621. 604. 740. 535.
 709. 648. 696. 666. 754. 651. 636. 708. 741. 746. 663. 711. 685. 751.
 698. 703. 671. 608. 693. 664. 660. 616. 622. 734. 738. 674. 644. 786.
 598. 629. 639. 826. 589. 590. 523. 650. 652. 672. 723. 667. 640. 653.
 678. 680. 659. 807. 765. 654. 757. 656. 578. 722. 677. 779. 702. 767.
 684. 637. 756. 742. 769. 760. 724. 704. 623. 737. 634. 576. 699. 641.
 707. 716. 712. 697. 627. 710. 763. 781. 679. 626. 752. 719. 575. 607.
 748. 725. 638. 580. 673. 571. 729. 646. 586. 772. 813. 687. 773. 610.
 606. 745. 603. 747. 686. 758. 591. 572. 549. 624. 755. 601. 775. 762.
 733. 597. 701. 568. 797. 730. 585. 713. 770. 594. 761. 768. 789. 596.
 615. 735. 820. 554. 545. 600. 774. 605. 547. 515. 625. 584. 588. 642.
 555. 732. 583. 776. 579. 782. 552. 822. 562. 787. 595. 766. 567. 587.
 847. 777. 573. 563. 592. 546. 800. 796. 593. 618. 559. 577. 785. 582.
 783. 542. 791. 806. 819. 534. 825. 556. 802. 533. 798. 810. 560. 780.
 804. 539. 537. 565. 778. 557. 818. 799. 811. 792. 812. 544.]

=== relacion_deuda_ingreso ===
[0.56 0.42 0.24 0.16 0.25 0.43 0.3  0.52 0.19 0.39 0.23 0.32 0.4  0.29
 0.13 0.41 0.48 0.44 0.21 0.46 0.5  0.38 0.53 0.12 0.2  0.22 0.36 0.59
 0.27 0.31 0.18 0.33 0.28 0.55 0.17 0.45 0.37 0.14 0.11 0.57 0.47 0.35
 0.1  0.34 0.54 0.15 0.6  0.51 0.26 0.58 0.49]

=== pago_prestamo ===
[125.77 454.19 971.82 ... 621.01 650.23 117.15]

=== monto_inversion ===
[689.22 360.34   0.   ... 587.44 286.47 966.6 ]

=== servicios_suscripcion ===
[3 4 5 9 8 7 2 6 1]

=== fondo_emergencia ===
[ 510.58 1154.41 1433.02 ...  780.17  712.12  902.69]

=== cantidad_transacciones ===
[68 41 90 94 73 56 69 65 99 91 53 86 74 58 66 59 62 96 35 82 64 27 31 22
 78 38 70 71 29 25 52 21 54 40 76 80 32 87 93 24 84 77 23 34 36 37 57 60
 50 89 45 51 63 61 88 49 97 75 83 46 81 92 79 43 47 44 20 28 98 42 39 55
 85 95 72 67 48 30 33 26]

=== indicador_fraude ===
[0 1]

=== gastos_discrecionales ===
[857.55 534.51 353.67 ... 275.53 373.85 695.36]

=== gastos_esenciales ===
[1910.85 3165.2  1504.56 ... 3231.56 2305.14 3142.37]

=== tipo_ingreso ===
<ArrowStringArray>
['Freelance', 'Salary', 'Mixed']
Length: 3, dtype: str

=== alquiler_o_hipoteca ===
[1501.65 1603.17 1097.82 ...  790.68  903.82  316.24]

=== categoria ===
<ArrowStringArray>
[   'Investments',     'Healthcare',      'Groceries',      'Utilities',
 'Transportation',  'Entertainment',      'Education',      'Insurance',
     'Dining Out',           'Rent']
Length: 10, dtype: str

=== estado_flujo_caja ===
<ArrowStringArray>
['Positive', 'Negative', 'Neutral']
Length: 3, dtype: str

=== puntaje_recomendacion_financiera ===
[  8.3  22.6  58.8  74.5  38.7  53.7  74.7  83.1  71.6  77.9  62.5  36.1
  39.   17.2  11.2  94.2  50.   68.6  90.6  73.7  43.5  79.7  81.4  78.3
  64.1  39.8  47.7  27.9  27.3  65.4  89.5  84.   98.8  80.7  88.5  62.6
  72.8  46.9  22.2  51.5   4.2  98.   11.9   5.2  39.9  66.   32.4  41.1
  27.8  67.7  54.3  23.   53.8   6.3  76.   87.6  68.3  77.3  37.1  23.8
  99.4  38.   25.8  45.2  72.3  97.4  62.2  73.8  50.3  33.8  96.9  55.7
  71.8  46.4  93.6  69.7   9.6  28.8  40.7   4.5  91.8  61.4  23.5  87.
  93.5  22.5  34.   63.3  10.7   1.   48.   98.9   8.8  97.7  57.6  45.5
  38.1  99.5  76.2   4.4  33.3   4.9  53.1   7.1  52.2  89.1  54.4  12.1
  15.6  58.3  25.4  11.4  99.7  31.7  31.5  19.1   1.3  76.4  91.4  64.3
  90.1  43.3  51.2  31.   93.2  21.4  95.1   5.9  83.2  31.2  90.5  56.4
  28.4   9.8  93.4  52.7  56.6  64.8  15.9  28.1  18.9  42.1  40.4  94.8
  14.4  13.   45.9  72.   13.9  61.9  82.8  91.5  44.7   5.7  78.2  50.4
  78.4  39.6  42.6  43.7  34.4  36.4  12.9  55.9  44.1  49.5  45.6  79.6
  42.4  28.7  35.9  37.9  45.8  20.2  49.6  95.    3.9  56.2  86.1  29.9
  84.9   7.9  33.7  77.   73.5  92.6  12.7  61.5  55.3   7.7   1.7  99.
  46.6  25.   12.2   8.9  58.1  10.5  50.7  81.7  63.8  11.7   6.2  41.6
  49.2  26.4  37.4  77.2  25.3  32.2  60.2  23.2  30.3  84.7  37.7  12.3
  16.6  10.2   4.7  71.   15.4  30.9  33.   76.6  10.   22.1  35.3  34.8
  88.8  46.3  59.   45.3  87.8  13.1  46.1  25.1  68.7  80.3  88.4  43.9
  50.2  30.1   6.1  79.8  52.8   4.1  14.5  94.5  91.   59.3  35.6  38.5
  14.2  24.   42.3   7.5  86.7  96.6  84.8  47.5  54.5  21.1  95.4  15.8
  95.5  26.   42.9  64.7  11.6  62.7  73.4  48.7  67.8  13.7  62.3   3.1
  43.2  56.5  99.3  90.7  22.8  53.4  43.4  78.1  63.2  12.6  47.3  55.6
   6.7  47.6  56.8  46.7  85.4  39.2  21.9  79.4  89.   41.7  59.9  47.2
  69.2  37.3  56.7   0.2   2.5  79.1   9.3  45.1  40.9  81.6  82.6  36.2
  63.7  10.8  93.8  10.1  96.1  26.9  75.1  41.2  75.3  69.5  41.5  95.8
  28.   73.6   8.5  55.2  13.2   8.   67.9  36.9  68.4   3.   56.3  63.1
  46.5  84.3   5.1  89.2  67.4  74.4  35.5  91.1  63.9  44.6  34.6  79.5
  70.6  60.5  36.8  47.9  24.9  61.8  15.3  24.3   2.3  54.8  88.1  48.2
  11.8   7.   99.8  94.6  42.8  23.7  97.2  77.5  20.8  10.6   4.6  82.2
  91.7  65.8  75.9  21.6   7.2  47.4  86.6  24.8  26.8   2.6  84.1  22.4
  23.4  11.5  18.   15.5  12.5  48.3  33.2  17.5  68.5  80.6  32.9  23.6
  71.4  64.2  59.7   5.3  75.6  11.1  40.2  20.7  81.1  55.4   9.9  30.5
  68.2  34.3  29.2  84.2  65.7  70.   73.1  54.6  31.1   1.8  71.9  61.3
  85.8   0.3  51.6  88.   27.1  85.3  24.6  37.    2.9  51.4  77.1  51.7
  78.6   4.3  78.   51.9  74.   14.8  34.2  55.5  80.5  10.4  31.4  67.2
   0.8  37.5  88.6  95.2  76.1  18.4  17.9  78.7  98.7  19.4  26.7  83.3
  49.3  49.4  22.   53.6  20.9   7.8  83.9   0.4  92.   85.7   6.5  74.1
  48.4  97.8  95.6  20.   69.6  75.7  25.9  45.   23.3  60.6  28.5   9.7
  73.   17.4  21.3   0.6  10.9  30.8  27.4  26.6  13.4  40.5   2.1  58.5
  69.4  70.2  30.4  91.9  35.4  26.5  76.3  37.6  55.8  71.5   9.4  81.5
  80.   63.4  72.5  18.8  71.2  66.3  79.3  68.1  44.9  27.2  24.4   1.5
  41.4  63.6  13.8  61.6  78.8  89.7  48.8  15.1  27.5  70.9  42.7  19.8
   6.8  90.8  60.4  34.9  44.3  32.6  12.8  20.5   7.6  58.6  81.    8.2
  33.1  75.4   1.2  62.1  14.6  18.6  73.2  14.    0.5  61.   39.7  39.4
  66.7  66.2  36.6  27.7  26.1  69.9  59.1  76.9  34.5  36.3  97.   29.
  85.6  88.7  45.4  15.2  92.5  88.9  94.   66.8  16.7  64.5  46.2  85.5
   9.1  78.5  62.4  52.   96.   80.4  19.7  79.2  62.   89.8   4.8  35.1
  26.3  32.8   6.6  74.9  14.3  44.4  92.8  74.2  30.7  47.8  86.5  35.7
  86.   82.7  72.4  76.7  57.9  25.7  40.   19.6  77.8  12.4  65.9  37.8
  78.9  29.7  14.1  94.3  33.4   1.9  81.3   2.8   1.1  76.5  62.8  32.3
  74.8  18.1  52.5  98.1  86.3  19.9  72.2  97.1  58.9  91.3  52.6  57.7
  70.1  11.3  82.9  83.6  97.6  69.1  40.6  66.1  67.6  51.1  34.1  82.1
  39.1  87.9  86.9  59.8  67.1  18.2   0.1  67.3  46.8  63.   54.1  79.
  27.6  13.5  87.3   7.3  72.7  70.5  97.5  38.3  38.4  42.   54.    1.6
   3.2  80.2  19.5  85.   98.3  53.9  36.5  75.2  13.3  38.8  25.2  57.5
  17.8  33.9  93.9  88.2  35.2  56.1  59.5  30.2  32.   57.1   3.8  25.6
  20.6  90.9  77.6  23.1   0.7  86.4  32.1   6.9   5.8  38.2  32.5  43.1
   8.7  97.3  76.8  50.5  99.1  80.8  87.2  58.7  75.5  53.5  50.6  39.5
  13.6  44.5  94.9  49.   98.5  31.8  65.1  86.8  65.3  81.2  24.1  56.
  57.2  98.2  22.3  72.6  93.7  18.3  50.1  57.   18.5  74.3  58.2  26.2
  87.1  21.2  59.4  93.3  43.   72.1  51.3   2.7  30.6  68.   42.5  69.3
  92.4  60.   91.2  80.9  44.   88.3  90.   92.1  90.4  58.4  31.9  68.8
  87.7  19.2  50.9  16.3   9.5  16.   81.8  16.2  29.5  64.   66.4   0.9
  10.3  18.7  39.3  41.3  53.    2.   90.2  17.3  22.9  69.8  15.   52.3
  83.5  35.   29.1  94.1  83.7   3.7  49.7  84.4  77.4  64.6  42.2  98.4
  75.8  66.6  29.8  74.6  16.9  90.3  71.3  40.8  93.1  16.8  60.3  71.7
  55.1  84.6   3.5  21.5   6.4  41.9  48.6  75.   51.   81.9  33.6  47.1
  19.3  15.7  70.3  85.1  37.2  96.8  54.2  14.9  53.2  96.5  57.4  99.9
  60.9  67.5  21.8  57.8  82.4  49.8  16.5  63.5  86.2   8.6  95.7  82.5
  82.3  70.7  28.2  87.4  97.9  36.   38.9  70.8  60.1  31.3   9.   41.
  64.9  50.8  49.9   8.1   5.   24.7  92.2  48.5  65.6  89.6  48.1  22.7
  29.3  12.   40.3  51.8  77.7 100.   28.6  99.2  79.9  92.9  72.9  28.3
  19.   17.7  83.4  49.1  47.   54.7  36.7  41.8  24.5  89.9  85.2  92.3
  71.1   6.   89.3  96.3  59.2  27.   70.4  94.4  93.   99.6  59.6  91.6
  65.2   2.2  52.9   8.4  84.5  57.3  55.   96.7   2.4  29.4   7.4  45.7
  61.7  65.5  32.7  34.7  17.1  44.8  67.   87.5  65.    5.4  95.9  94.7
  69.   89.4  21.   16.4   1.4  80.1  48.9  85.9  23.9  66.5  98.6  24.2
  46.   83.8  31.6  28.9]

=== nivel_estres_financiero ===
<ArrowStringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str

=== ahorro_real ===
[   0.   1179.2  2424.29 ... 2570.27  463.05  543.23]

=== meta_ahorro_cumplida ===
[0 1]

In [8]:
# Escenario financiero
df2["escenario_financiero"] = df2["escenario_financiero"].replace({
    "inflation": "Inflación",
    "normal": "Normal",
    "recession": "Recesión"
})

# Tipo de ingreso
df2["tipo_ingreso"] = df2["tipo_ingreso"].replace({
    "Freelance": "Independiente",
    "Salary": "Salario",
    "Mixed": "Mixto"
})

# Categoría
df2["categoria"] = df2["categoria"].replace({
    "Investments": "Inversiones",
    "Healthcare": "Salud",
    "Groceries": "Alimentacion",
    "Utilities": "Servicios",
    "Transportation": "Transporte",
    "Entertainment": "Ocio",
    "Education": "Educacion",
    "Insurance": "Otros",
    "Dining Out": "Gastos_hormiga",
    "Rent": "Vivienda"
})

# Estado del flujo de caja
df2["estado_flujo_caja"] = df2["estado_flujo_caja"].replace({
    "Positive": "Positivo",
    "Negative": "Negativo",
    "Neutral": "Neutral"
})

# Nivel de estrés financiero
df2["nivel_estres_financiero"] = df2["nivel_estres_financiero"].replace({
    "Low": "Bajo",
    "Medium": "Medio",
    "High": "Alto"
})
for columna in [
    "escenario_financiero",
    "tipo_ingreso",
    "categoria",
    "estado_flujo_caja",
    "nivel_estres_financiero"
]:
    print(f"\n{columna}:")
    print(df2[columna].unique())

escenario_financiero:
<ArrowStringArray>
['Inflación', 'Normal', 'Recesión']
Length: 3, dtype: str

tipo_ingreso:
<ArrowStringArray>
['Independiente', 'Salario', 'Mixto']
Length: 3, dtype: str

categoria:
<ArrowStringArray>
[   'Inversiones',          'Salud',   'Alimentacion',      'Servicios',
     'Transporte',           'Ocio',      'Educacion',          'Otros',
 'Gastos_hormiga',       'Vivienda']
Length: 10, dtype: str

estado_flujo_caja:
<ArrowStringArray>
['Positivo', 'Negativo', 'Neutral']
Length: 3, dtype: str

nivel_estres_financiero:
<ArrowStringArray>
['Bajo', 'Alto', 'Medio']
Length: 3, dtype: str

In [9]:
pd.set_option('display.max_columns', None)
df2

,fecha,id_usuario,ingreso_mensual,gasto_mensual_total,tasa_ahorro,objetivo_presupuesto,escenario_financiero,puntaje_crediticio,relacion_deuda_ingreso,pago_prestamo,monto_inversion,servicios_suscripcion,fondo_emergencia,cantidad_transacciones,indicador_fraude,gastos_discrecionales,gastos_esenciales,tipo_ingreso,alquiler_o_hipoteca,categoria,estado_flujo_caja,puntaje_recomendacion_financiera,nivel_estres_financiero,ahorro_real,meta_ahorro_cumplida
0,2019-01-01,1584,3119.58,3212.07,0.38,3676.11,Inflación,721.0,0.56,125.77,689.22,3,510.58,68,0,857.55,1910.85,Independiente,1501.65,Inversiones,Positivo,8.3,Bajo,0.00,0
1,2019-01-31,1045,3262.44,3732.81,0.10,2607.17,Inflación,670.0,0.42,454.19,360.34,4,1154.41,41,0,534.51,3165.20,Salario,1603.17,Inversiones,Positivo,22.6,Bajo,0.00,0
2,2019-03-02,1756,2931.20,3335.58,0.15,3004.14,Inflación,691.0,0.24,971.82,0.00,5,1433.02,90,0,353.67,1504.56,Independiente,1097.82,Salud,Positivo,58.8,Bajo,0.00,0
3,2019-04-01,1724,3506.79,2327.59,0.17,3346.97,Normal,717.0,0.16,482.76,182.06,5,227.37,94,0,594.08,1450.72,Independiente,1155.64,Alimentacion,Positivo,74.5,Bajo,1179.20,0
4,2019-05-01,1600,4606.87,2182.58,0.34,2670.09,Inflación,795.0,0.25,263.74,342.78,9,589.81,73,0,556.86,1000.00,Salario,1170.86,Servicios,Negativo,38.7,Alto,2424.29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2023-07-09,1822,3254.55,3992.02,0.17,2675.77,Normal,704.0,0.30,285.16,597.74,9,466.11,81,0,408.23,2088.32,Mixto,2079.99,Salud,Positivo,43.2,Bajo,0.00,0
2996,2023-08-08,1907,2752.78,5685.18,0.26,2682.99,Recesión,697.0,0.12,417.06,587.44,7,807.86,21,0,167.78,2445.34,Salario,832.95,Ocio,Neutral,46.0,Bajo,0.00,0
2997,2023-09-07,1464,3691.10,3228.05,0.12,3893.53,Normal,626.0,0.12,621.01,286.47,6,780.17,34,0,275.53,3231.56,Salario,790.68,Servicios,Neutral,40.7,Medio,463.05,0
2998,2023-10-07,1346,3133.24,4335.72,0.08,2854.72,Inflación,628.0,0.42,650.23,966.60,2,712.12,92,0,373.85,2305.14,Salario,903.82,Servicios,Positivo,57.1,Bajo,0.00,0
2999,2023-11-06,1140,4090.06,3546.83,0.23,2365.61,Normal,655.0,0.46,117.15,0.00,5,902.69,78,0,695.36,3142.37,Salario,316.24,Ocio,Positivo,54.8,Bajo,543.23,0

ETIQUETADO DEL PERFIL FINANCIERO

In [10]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# ==========================================================
# COPIA DEL DATASET
# ==========================================================

df = df2.copy()

# ==========================================================
# VARIABLES A NORMALIZAR
# ==========================================================

columnas_normalizar = [

    "ingreso_mensual",
    "gasto_mensual_total",
    "tasa_ahorro",
    "objetivo_presupuesto",
    "relacion_deuda_ingreso",
    "pago_prestamo",
    "monto_inversion",
    "servicios_suscripcion",
    "fondo_emergencia",
    "cantidad_transacciones",
    "gastos_discrecionales",
    "gastos_esenciales",
    "alquiler_o_hipoteca",
    "ahorro_real"

]

# ==========================================================
# NORMALIZACIÓN (SOLO COLUMNAS AUXILIARES)
# ==========================================================

scaler = MinMaxScaler()

df_norm = pd.DataFrame(

    scaler.fit_transform(df[columnas_normalizar]),

    columns=[

        columna + "_norm"

        for columna in columnas_normalizar

    ],

    index=df.index

)

df = pd.concat(

    [df, df_norm],

    axis=1

)

# ==========================================================
# VARIABLES CATEGÓRICAS AUXILIARES
# ==========================================================

mapa_flujo = {

    "Positivo": 1.0,
    "Neutral": 0.5,
    "Negativo": 0.0

}

mapa_estres = {

    "Bajo": 1.0,
    "Medio": 0.5,
    "Alto": 0.0

}

mapa_tipo = {

    "Mixto": 1.0,
    "Salario": 0.8,
    "Independiente": 0.6

}

df["estado_flujo_caja_score"] = (

    df["estado_flujo_caja"]

    .map(mapa_flujo)

)

df["nivel_estres_score"] = (

    df["nivel_estres_financiero"]

    .map(mapa_estres)

)

df["tipo_ingreso_score"] = (

    df["tipo_ingreso"]

    .map(mapa_tipo)

)

# ==========================================================
# ÍNDICE FINANCIERO
# ==========================================================

df["indice_financiero"] = (

      df["ingreso_mensual_norm"] * 10

    + (1 - df["gasto_mensual_total_norm"]) * 10

    + df["tasa_ahorro_norm"] * 18

    + (1 - df["relacion_deuda_ingreso_norm"]) * 18

    + (1 - df["pago_prestamo_norm"]) * 6

    + df["monto_inversion_norm"] * 8

    + (1 - df["servicios_suscripcion_norm"]) * 2

    + df["fondo_emergencia_norm"] * 8

    + (1 - df["gastos_discrecionales_norm"]) * 5

    + (1 - df["gastos_esenciales_norm"]) * 4

    + (1 - df["alquiler_o_hipoteca_norm"]) * 3

    + df["ahorro_real_norm"] * 4

    + df["estado_flujo_caja_score"] * 2

    + df["nivel_estres_score"] * 1

    + df["tipo_ingreso_score"] * 1

)

# ==========================================================
# AJUSTES DEL ÍNDICE
# ==========================================================

df["indice_financiero"] += (

    (

        1 -

        abs(

            df["objetivo_presupuesto_norm"]

            -

            df["ingreso_mensual_norm"]

        )

    ) * 3

)

df["indice_financiero"] += (

    df["meta_ahorro_cumplida"] * 2

)

df["indice_financiero"] = (

    df["indice_financiero"]

    .clip(0, 100)

)

# ==========================================================
# REVISIÓN DEL ÍNDICE
# ==========================================================

print("\nResumen del índice financiero\n")

print(

    df["indice_financiero"]

    .describe()

)

print("\nPrimeros registros\n")

print(

    df[[

        "ingreso_mensual",
        "gasto_mensual_total",
        "tasa_ahorro",
        "indice_financiero"

    ]].head()

)
# CREACIÓN DEL PERFIL FINANCIERO
# ==========================================================

# ----------------------------------------------------------
# CÁLCULO DE PERCENTILES
# ----------------------------------------------------------

p10 = df["indice_financiero"].quantile(0.10)
p30 = df["indice_financiero"].quantile(0.30)
p55 = df["indice_financiero"].quantile(0.55)
p75 = df["indice_financiero"].quantile(0.75)
p90 = df["indice_financiero"].quantile(0.90)

print("\nPercentiles")
print("--------------------------")
print(f"P10: {p10:.2f}")
print(f"P30: {p30:.2f}")
print(f"P55: {p55:.2f}")
print(f"P75: {p75:.2f}")
print(f"P90: {p90:.2f}")

# ----------------------------------------------------------
# FUNCIÓN DE ETIQUETADO
# ----------------------------------------------------------

def clasificar_perfil(indice):

    if indice <= p10:
        return "Crítico"

    elif indice <= p30:
        return "En riesgo"

    elif indice <= p55:
        return "En observación"

    elif indice <= p75:
        return "Estable"

    elif indice <= p90:
        return "Saludable"

    else:
        return "Excelente"

# ----------------------------------------------------------
# CREAR PERFIL FINANCIERO
# ----------------------------------------------------------

df["perfil_financiero"] = df["indice_financiero"].apply(
    clasificar_perfil
)

# ----------------------------------------------------------
# DISTRIBUCIÓN DE CLASES
# ----------------------------------------------------------

print("\nDistribución de perfiles")
print("--------------------------------")

print(df["perfil_financiero"].value_counts())

print("\nPorcentaje")

print(

    round(

        df["perfil_financiero"]

        .value_counts(normalize=True)

        *100,

        2

    )

)

# ----------------------------------------------------------
# ELIMINAR COLUMNAS AUXILIARES
# ----------------------------------------------------------

columnas_auxiliares = [

    columna + "_norm"

    for columna in columnas_normalizar

]

columnas_auxiliares += [

    "estado_flujo_caja_score",

    "nivel_estres_score",

    "tipo_ingreso_score"

]

df.drop(

    columns=columnas_auxiliares,

    inplace=True

)

# ----------------------------------------------------------
# REVISAR DATASET FINAL
# ----------------------------------------------------------

print("\nColumnas finales")

print(df.columns.tolist())

print("\nPrimeros registros")

print(df.head())

# ----------------------------------------------------------
# GUARDAR DATASET
# ----------------------------------------------------------

df.to_csv(

    "datasets/df_modelo_pf.csv",

    index=False

)

print("\n=========================================")
print("Dataset etiquetado guardado correctamente")
print("=========================================")

Resumen del índice financiero

count    3000.000000
mean       51.312420
std         8.539211
min        25.784765
25%        45.528431
50%        51.120958
75%        57.236037
max        77.725431
Name: indice_financiero, dtype: float64

Primeros registros

   ingreso_mensual  gasto_mensual_total  tasa_ahorro  indice_financiero
0          3119.58              3212.07         0.38          50.345998
1          3262.44              3732.81         0.10          39.294951
2          2931.20              3335.58         0.15          47.056776
3          3506.79              2327.59         0.17          53.087863
4          4606.87              2182.58         0.34          61.782912

Percentiles
--------------------------
P10: 40.23
P30: 46.63
P55: 52.35
P75: 57.24
P90: 62.46

Distribución de perfiles
--------------------------------
perfil_financiero
En observación    750
Estable           600
En riesgo         600
Saludable         450
Crítico           300
Excelente         300
Name: count, dtype: int64

Porcentaje
perfil_financiero
En observación    25.0
Estable           20.0
En riesgo         20.0
Saludable         15.0
Crítico           10.0
Excelente         10.0
Name: proportion, dtype: float64

Columnas finales
['fecha', 'id_usuario', 'ingreso_mensual', 'gasto_mensual_total', 'tasa_ahorro', 'objetivo_presupuesto', 'escenario_financiero', 'puntaje_crediticio', 'relacion_deuda_ingreso', 'pago_prestamo', 'monto_inversion', 'servicios_suscripcion', 'fondo_emergencia', 'cantidad_transacciones', 'indicador_fraude', 'gastos_discrecionales', 'gastos_esenciales', 'tipo_ingreso', 'alquiler_o_hipoteca', 'categoria', 'estado_flujo_caja', 'puntaje_recomendacion_financiera', 'nivel_estres_financiero', 'ahorro_real', 'meta_ahorro_cumplida', 'indice_financiero', 'perfil_financiero']

Primeros registros
        fecha  id_usuario  ingreso_mensual  gasto_mensual_total  tasa_ahorro  \
0  2019-01-01        1584          3119.58              3212.07         0.38
1  2019-01-31        1045          3262.44              3732.81         0.10
2  2019-03-02        1756          2931.20              3335.58         0.15
3  2019-04-01        1724          3506.79              2327.59         0.17
4  2019-05-01        1600          4606.87              2182.58         0.34

   objetivo_presupuesto escenario_financiero  puntaje_crediticio  \
0               3676.11            Inflación               721.0
1               2607.17            Inflación               670.0
2               3004.14            Inflación               691.0
3               3346.97               Normal               717.0
4               2670.09            Inflación               795.0

   relacion_deuda_ingreso  pago_prestamo  monto_inversion  \
0                    0.56         125.77           689.22
1                    0.42         454.19           360.34
2                    0.24         971.82             0.00
3                    0.16         482.76           182.06
4                    0.25         263.74           342.78

   servicios_suscripcion  fondo_emergencia  cantidad_transacciones  \
0                      3            510.58                      68
1                      4           1154.41                      41
2                      5           1433.02                      90
3                      5            227.37                      94
4                      9            589.81                      73

   indicador_fraude  gastos_discrecionales  gastos_esenciales   tipo_ingreso  \
0                 0                 857.55            1910.85  Independiente
1                 0                 534.51            3165.20        Salario
2                 0                 353.67            1504.56  Independiente
3                 0                 594.08            1450.72  Independiente
4                 0                 556.86            1000.00        Salario

   alquiler_o_hipoteca     categoria estado_flujo_caja  \
0              1501.65   Inversiones          Positivo
1              1603.17   Inversiones          Positivo
2              1097.82         Salud          Positivo
3              1155.64  Alimentacion          Positivo
4              1170.86     Servicios          Negativo

   puntaje_recomendacion_financiera nivel_estres_financiero  ahorro_real  \
0                               8.3                    Bajo         0.00
1                              22.6                    Bajo         0.00
2                              58.8                    Bajo         0.00
3                              74.5                    Bajo      1179.20
4                              38.7                    Alto      2424.29

   meta_ahorro_cumplida  indice_financiero perfil_financiero
0                     0          50.345998    En observación
1                     0          39.294951           Crítico
2                     0          47.056776    En observación
3                     0          53.087863           Estable
4                     0          61.782912         Saludable

=========================================
Dataset etiquetado guardado correctamente
=========================================

# Transformando entrada de datos del usuario

Hacer un clasificador de ingresos de esta manera sabemos más acerca del perfil financiero de la persona

In [21]:
#Se recibe la tabla desde Backend
datos = {
    "fecha": [
        "2026-07-01",
        "2026-07-02",
        "2026-07-03",
        "2026-07-04",
        "2026-07-05",
        "2026-07-06",
        "2026-07-07",
        "2026-07-08",
        "2026-07-09",
        "2026-07-10",
        "2026-07-01"
    ],
    
    "descripcion": [
        "Sueldo mensual recibido",
        "Mercado Éxito",
        "Pago de energía",
        "Honorarios por consultoría",
        "Netflix",
        "Cobro de cliente",
        "Arriendo apartamento",
        "Gasolina",
        "Depósito de nómina",
        "Restaurante",
        "aporte a inversion"
    ],
    
    "categoria": [
        "Ingresos",
        "Alimentacion",
        "Servicios",
        "Ingresos",
        "Ocio",
        "Ingresos",
        "Vivienda",
        "Transporte",
        "Ingresos",
        "Gastos_hormiga",
        "Aporte_inversiones"
    ],
    
    "valor": [
        32,
        180,
        95,
        850,
        28,
        500,
        90,
        70,
        320,
        4.5,
        200
    ]
}

df_usuario = pd.DataFrame(datos)

print(df_usuario)

         fecha                 descripcion           categoria  valor
0   2026-07-01     Sueldo mensual recibido            Ingresos   32.0
1   2026-07-02               Mercado Éxito        Alimentacion  180.0
2   2026-07-03             Pago de energía           Servicios   95.0
3   2026-07-04  Honorarios por consultoría            Ingresos  850.0
4   2026-07-05                     Netflix                Ocio   28.0
5   2026-07-06            Cobro de cliente            Ingresos  500.0
6   2026-07-07        Arriendo apartamento            Vivienda   90.0
7   2026-07-08                    Gasolina          Transporte   70.0
8   2026-07-09          Depósito de nómina            Ingresos  320.0
9   2026-07-10                 Restaurante      Gastos_hormiga    4.5
10  2026-07-01          aporte a inversion  Aporte_inversiones  200.0

In [22]:
modelo_tipo_ingreso_cat = joblib.load("modelos/modelo_tipo_ingreso_1.pkl")
modelo_tipo_ingreso = joblib.load("modelos/modelo_tipo_ingreso_2.pkl")

In [23]:
#Analisis si hay o no ingresos
df_usuario["tipo_ingreso"] = None

# Filtrar solo las filas cuya categoría sea "Ingresos"
mask = df_usuario["categoria"] == "Ingresos"

# Si existen ingresos, clasificarlos
if mask.any():
    df_usuario.loc[mask, "tipo_ingreso_1"] = modelo_tipo_ingreso_cat.predict(
        df_usuario.loc[mask, "descripcion"]
    )

#Analisis si hay o no ingresos
df_usuario["tipo_ingreso"] = None

# Filtrar solo las filas cuya categoría no sea none
mask = df_usuario["tipo_ingreso_1"].notna()

# Si existen ingresos, clasificarlos
if mask.any():
    df_usuario.loc[mask, "tipo_ingreso"] = modelo_tipo_ingreso.predict(
        df_usuario.loc[mask, "tipo_ingreso_1"]
    )

# Para armar array que entra para perfil financiero tipo_ingreso

tipos = set(df_usuario["tipo_ingreso"].dropna())

if len(tipos) == 0:
    perfil_ingreso = "Sin ingresos registrados"
elif tipos == {"Salario"}:
    perfil_ingreso = "Salario"
elif tipos == {"Independiente"}:
    perfil_ingreso = "Independiente"
else:
    perfil_ingreso = "Mixto"

print(perfil_ingreso)

# Reemplazar la categoría con tipo_ingreso_1 cuando este no sea nulo
df_usuario["categoria"] = df_usuario["tipo_ingreso_1"].fillna(df_usuario["categoria"])

# Eliminar la columna tipo_ingreso_1
df_usuario.drop(columns=["tipo_ingreso_1"], inplace=True)

transacciones=df_usuario

Mixto

In [24]:
transacciones

,fecha,descripcion,categoria,valor,tipo_ingreso
0,2026-07-01,Sueldo mensual recibido,Salario,32.0,Salario
1,2026-07-02,Mercado Éxito,Alimentacion,180.0,None
2,2026-07-03,Pago de energía,Servicios,95.0,None
3,2026-07-04,Honorarios por consultoría,Honorarios,850.0,Independiente
4,2026-07-05,Netflix,Ocio,28.0,None
5,2026-07-06,Cobro de cliente,Negocio,500.0,Independiente
6,2026-07-07,Arriendo apartamento,Vivienda,90.0,None
7,2026-07-08,Gasolina,Transporte,70.0,None
8,2026-07-09,Depósito de nómina,Salario,320.0,Salario
9,2026-07-10,Restaurante,Gastos_hormiga,4.5,None
10,2026-07-01,aporte a inversion,Aporte_inversiones,200.0,None

# Perfil Financiero

Transformar lo entrante para poderlo insertar en el modelo

In [ ]:
columnas_modelo = [
    "ingreso_mensual",
    "gasto_mensual_total",
    "tasa_ahorro",
    "objetivo_presupuesto",
    "relacion_deuda_ingreso",
    "pago_prestamo",
    "monto_inversion",
    "servicios_suscripcion",
    "fondo_emergencia",
    "cantidad_transacciones",
    "gastos_discrecionales",
    "gastos_esenciales",
    "tipo_ingreso",
    "alquiler_o_hipoteca",
    "estado_flujo_caja",
    "nivel_estres_financiero",
    "ahorro_real"
]
def generar_caracteristicas_usuario(
    ingreso_mensual,
    deuda_total,
    objetivo_presupuesto,
    pago_prestamo,
    servicios_suscripcion,
    fondo_emergencia,
    monto_inversion,
    transacciones
):

    categorias_ingreso = [
        "Honorarios",
        "Rendimiento_inversiones",
        "Negocio",
        "Otros_Ingresos",
        "Salario",
        "Subsidios"
    ]

    # Separar ingresos y gastos
    ingresos = transacciones[
        transacciones["categoria"].isin(categorias_ingreso)
    ]

    gastos = transacciones[
        ~transacciones["categoria"].isin(categorias_ingreso)
    ]


    # =========================
    # Cálculos financieros
    # =========================

    gasto_mensual_total = gastos["valor"].sum()


    gastos_esenciales = gastos.loc[
        gastos["categoria"].isin([
            "Alimentacion",
            "Educacion",
            "Salud",
            "Servicios",
            "Transporte",
            "Vivienda"
        ]),
        "valor"
    ].sum()


    gastos_discrecionales = gastos.loc[
        gastos["categoria"].isin([
            "Ocio",
            "Gastos_hormiga",
            "Otros"
        ]),
        "valor"
    ].sum()
    
    aporte_inversiones = gastos.loc[gastos["categoria"] == "Aporte_inversiones","valor"].sum()


    ahorro_real = ingreso_mensual - gasto_mensual_total + aporte_inversiones


    tasa_ahorro = (
        ahorro_real / ingreso_mensual
        if ingreso_mensual > 0 else 0
    )


    relacion_deuda_ingreso = (
        deuda_total / ingreso_mensual
        if ingreso_mensual > 0 else 0
    )
    
    
    # =========================
    # Inversiones
    # =========================

    monto_inversion = monto_inversion + aporte_inversiones

    # =========================
    # Vivienda
    # =========================

    alquiler_o_hipoteca = gastos.loc[
        gastos["categoria"] == "Vivienda",
        "valor"
    ].sum()



    # =========================
    # Flujo de caja
    # =========================

    if ahorro_real > 0:
        estado_flujo_caja = "Positivo"

    elif ahorro_real < 0:
        estado_flujo_caja = "Negativo"

    else:
        estado_flujo_caja = "Neutral"



    # =========================
    # Tipo de ingreso
    # =========================

    categorias_presentes = set(
        ingresos["categoria"]
    )


    tiene_salario = (
        "Salario" in categorias_presentes
    )


    tiene_independiente = len(
        categorias_presentes.intersection({
            "Honorarios",
            "Negocio",
            "Subsidios",
            "Rendimiento_inversiones",
            "Otros_Ingresos"
        })
    ) > 0



    if tiene_salario and tiene_independiente:
        tipo_ingreso = "Mixto"

    elif tiene_salario:
        tipo_ingreso = "Salario"

    elif tiene_independiente:
        tipo_ingreso = "Independiente"

    else:
        tipo_ingreso = "Sin ingreso"


    # =========================
    # Nivel de estrés financiero
    # Regla inicial
    # =========================

    porcentaje_deuda = relacion_deuda_ingreso

    if porcentaje_deuda > 0.5 or ahorro_real < 0:
        nivel_estres_financiero = "Alto"

    elif porcentaje_deuda > 0.3:
        nivel_estres_financiero = "Medio"

    else:
        nivel_estres_financiero = "Bajo"



    # =========================
    # Dataset final modelo
    # =========================

    datos_modelo = pd.DataFrame({

        "ingreso_mensual": [
            ingreso_mensual
        ],

        "gasto_mensual_total": [
            gasto_mensual_total
        ],

        "tasa_ahorro": [
            tasa_ahorro
        ],

        "objetivo_presupuesto": [
            objetivo_presupuesto
        ],

        "relacion_deuda_ingreso": [
            relacion_deuda_ingreso
        ],

        "pago_prestamo": [
            pago_prestamo
        ],

        "monto_inversion": [
            monto_inversion
        ],

        "servicios_suscripcion": [
            servicios_suscripcion
        ],

        "fondo_emergencia": [
            fondo_emergencia
        ],

        "cantidad_transacciones": [
            len(transacciones)
        ],

        "gastos_discrecionales": [
            gastos_discrecionales
        ],

        "gastos_esenciales": [
            gastos_esenciales
        ],

        "tipo_ingreso": [
            tipo_ingreso
        ],

        "alquiler_o_hipoteca": [
            alquiler_o_hipoteca
        ],

        "estado_flujo_caja": [
            estado_flujo_caja
        ],

        "nivel_estres_financiero": [
            nivel_estres_financiero
        ],

        "ahorro_real": [
            ahorro_real
        ]

    })

    return datos_modelo[columnas_modelo]

In [31]:
datos2  = generar_caracteristicas_usuario(
    ingreso_mensual=3000,
    deuda_total=1000,
    objetivo_presupuesto=500,
    pago_prestamo=200,
    servicios_suscripcion=2,
    fondo_emergencia=1500,
    monto_inversion=300,
    transacciones=transacciones
)

print(datos2)

   ingreso_mensual  gasto_mensual_total  tasa_ahorro  objetivo_presupuesto  \
0             3000                667.5     0.844167                   500

   relacion_deuda_ingreso  pago_prestamo  monto_inversion  \
0                0.333333            200            500.0

   servicios_suscripcion  fondo_emergencia  cantidad_transacciones  \
0                      2              1500                      11

   gastos_discrecionales  gastos_esenciales tipo_ingreso  alquiler_o_hipoteca  \
0                   32.5              435.0        Mixto                 90.0

  estado_flujo_caja nivel_estres_financiero  ahorro_real
0          Positivo                   Medio       2532.5

In [32]:
datos2.columns
datos2.dtypes
datos2.columns.tolist()

['ingreso_mensual',
 'gasto_mensual_total',
 'tasa_ahorro',
 'objetivo_presupuesto',
 'relacion_deuda_ingreso',
 'pago_prestamo',
 'monto_inversion',
 'servicios_suscripcion',
 'fondo_emergencia',
 'cantidad_transacciones',
 'gastos_discrecionales',
 'gastos_esenciales',
 'tipo_ingreso',
 'alquiler_o_hipoteca',
 'estado_flujo_caja',
 'nivel_estres_financiero',
 'ahorro_real']

In [33]:
modelo_pf = joblib.load("modelos/perfil_financiero.pkl")

## Tabla de Perfil Financiero
🟢 Excelente
🟢 Saludable 
🟡 Estable 
🟠 En observación 
🔴 En riesgo 
⚫ Crítico

In [34]:
perfil_financiero = modelo_pf.predict(datos2)

clases = modelo_pf.classes_

probabilidades = modelo_pf.predict_proba(datos2)[0]

resultado = dict(zip(clases, probabilidades))

print(resultado)
print(perfil_financiero)

{'Crítico': 0.013333333333333334, 'En observación': 0.05333333333333334, 'En riesgo': 0.02, 'Estable': 0.20666666666666667, 'Excelente': 0.39666666666666667, 'Saludable': 0.31}
['Excelente']